---
# CentOS 7 LAMP Stack
# Author: Arockiasamy K
# Version: 1.0

# - name: Apply for common configuration to all the nodes
#   hosts: all
#   remote_user: root

#   roles:
#    - common
   
- name: deploy MySQL and configure databases
  hosts: dbservers
  remote_user: root
  become: true
   
  roles:
   - db
   
- name: deploy Apache, PHP and configure website code
  hosts: webservers
  remote_user: root
  become: true
  tags: web
   
  roles:
   - web

- name: deploy wordpress
  hosts: webservers
  remote_user: root
  become: true
  tags: wordpress
   
  roles:
   - wordpress